### PR TITLE
Reintroduce 'ROOTAPI' so domain and protocol can be configured

### PR DESCRIPTION
**Pull request by McJoppy**
eg. setter for api root added as comment in examples/BASIC/BASIC.ino

### CODE REVIEW

**Comment by airgradienthq** [comment]
@pnt325 Is that change also in the other example files?

**Comment by pnt325** [comment]
> @pnt325 Is that change also in the other example files?

Yes, all example that use http client need to update. This PR update for `BASIC.ino` only

**Comment by McJoppy** [comment]
I only have the ability to test on hardware using the basic example which is why I only updated that.

I'll add the changes to the other examples too.

**Comment by airgradienthq** [comment]
@McJoppy Are you updating the pull request with the other examples too?

**Comment by McJoppy** [comment]
I've now included comments in each example for changing APIROOT to align with `BASIC.ino`

**Pull request merged**
