### PR TITLE
Update AQI breakpoints to 2024 values

### PR DESCRIPTION
**Pull request by MallocArray**
#207 

Update breakpoints to follow EPA guidelines from 2024

Also correct the formula to follow what is published on Wikipedia which changes a few values by 1 or 0.1 to match the existing breakpoints, such as Index low previously being 50 when the link shows it should be 51

https://www.epa.gov/system/files/documents/2024-02/pm-naaqs-air-quality-index-fact-sheet.pdf
https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI

### CODE REVIEW

**Comment by airgradienthq** [comment]
@MallocArray Thank you for contributing this. We will merge it in parallel of the adjustments we will need to do on the AirGradient dashboard side.

**Comment by airgradienthq** [comment]
@MallocArray is there a reason why you have the upper limit capped at 325 ug/m3?
The PMS sensor delivers data up to 500. Shouldn't we increase that number?

`  else if (pm02 <= 325.4)`

**Comment by airgradienthq** [comment]
There is the term "beyond index" by the EPA see for example:
https://2009-2017.state.gov/m/pri/gdi/airquality/c70218.htm

Also here it seems the newer version does not have the 500 as upper cap anymore:
image

https://www.epa.gov/system/files/documents/2024-02/pm-naaqs-air-quality-index-fact-sheet.pdf

I would recommend that we do not cap at 500.

**Comment by MallocArray** [comment]
Thank you for the links.  It also brought me to the AirNow calculator which also does not cap at 500.
https://www.airnow.gov/aqi/aqi-calculator-concentration/

I'll revise the PR to no longer have an upper limit

**Comment by samuelbles07** [comment]
We will merge and make the change to accept values higher more than 500

**Pull request merged**
